"use client";

import "@/styles/globals.css";
import { Amplify } from "aws-amplify";
import type { AppProps } from "next/app";
import config from "@/amplifyconfiguration.json";
import { withAuthenticator } from "@aws-amplify/ui-react";

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config, { ssr: true });

function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

export default withAuthenticator(App);
